version: "3.8"

services:
  db-headless:
    build:
      context: ./
      dockerfile: DockerfileDB
    container_name: db-headless
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_USER=${WORDPRESS_DB_USER}
    # image: mariadb
    user: 1000:1000
    volumes:
      - ./docker/db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  wp-headless:
    build: .
    command: bash -c 'install_wordpress && apache2-foreground'
    container_name: wp-headless
    depends_on:
      - db-headless
    env_file: ./.env
    ports:
      - "8080:8080"
    user: 1000:1000
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
      - ./docker/plugins:/var/www/plugins
